version: '3'
services:
  # 服务器资源太少跑不起来，暂时禁用了
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   ports:
  #     - '8347:3000'
  #   volumes:
  #     - ./web:/app
  #     - /app/node_modules
  #   container_name: crawler-novel-web
  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - '7873:8989'
    container_name: crawler-novel-java
    volumes:
      - ~/.m2/repository:/root/.m2/repository
      - ./crawler_plugin_res:/opt/novel_crawler/plugin