server:
  port: 8989

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # todo: 初始化-需要重新填写数据库信息
    username:
    password:
    url: jdbc:mysql://localhost:3306/?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 20
      auto-commit: true
      pool-name: HikariCP
      max-lifetime: 30000
      connection-timeout: 60000
      connection-test-query: select 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

springdoc:
  default-flat-param-object: true
  api-docs:
    enabled: true # 是否开启接口文档
#  swagger-ui:
#    # 持久化认证数据，如果设置为 true，它会保留授权数据并且不会在浏览器关闭/刷新时丢失
#    persistAuthorization: true

# http://127.0.0.1:8989/swagger-ui/index.html
# http://127.0.0.1:8989/doc.html
# https://juejin.cn/post/7214015651828006967#heading-7


config:
  business:
    prefix: xx